agents:
- damage_steps: 5
  id: 1
  is_adversarial: true
  motion_equation: 9
- id: 2
  motion_equation: 9
- id: 3
  motion_equation: 9
- id: 4
  motion_equation: 9
- id: 5
  motion_equation: 9
map_file_name: data/maze-32-32-4.map
permutations: 2
robust_route: 5
