agents:
- damage_steps: 3
  id: 1
  is_adversarial: true
  motion_equation: 9
- id: 2
  motion_equation: 9
- id: 3
  motion_equation: 9
- id: 4
  motion_equation: 9
- id: 5
  motion_equation: 9
map_file_name: data/Room1_56x55.txt
permutations: 10
robust_route: 3
