agents:
- damage_steps: 3
  id: 1
  is_adversarial: true
  motion_equation: 5
- id: 2
  motion_equation: 5
- id: 3
  motion_equation: 5
map_file_name: data/den407d.map
permutations: 5
robust_route: 3
