agents:
- damage_steps: 3
  id: 1
  is_adversarial: true
  motion_equation: 9
- id: 2
  motion_equation: 9
- id: 3
  motion_equation: 9
map_file_name: data/den312d.map
permutations: 6
robust_route: 3
